# fly.toml app configuration file generated for shopihood on 2023-07-11T16:49:58+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "shopihood"
primary_region = "ewr"
console_command = "/rails/bin/rails console"

[deploy]
  release_command = "./bin/rails db:prepare && ./bin/rails db:migrate"

[processes]
  app = "./bin/rails server"
  sidekiq = "bundle exec sidekiq"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[statics]]
  guest_path = "/rails/public"
  url_prefix = "/"
